spring:
  datasource:
    url: jdbc:mysql://localhost:3306/programmingcorner
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect